export const tagTypes = {
  AUTH: "Auth",
  ADMIN: "Admins",
  TOKENIZATIONS: "tokenization",
  STAKEHOLDERS: "stakeholders",
  COUNTRYlIST: "country",
  MINTINGLIST: "mintingUsers",
  ORGANIZATION: "Organizations",
  USERS: "Users",
  JOBS: "jobs",
  DISTRIBUTIONS: "distributions",
  FUND_RELEASES: "fundReleases",
  VAULT_SIGNER_SECRETS: "vaultSignerSecrets",
  VAULT_SIGNER_PERSONAL_ENVS: "vaultSignerPersonalEnvs",
  VAULT_SIGNER_MANAGED_SECRETS: "vaultSignerManagedSecrets",
  VAULT_SIGNER_ASSIGNMENTS: "vaultSignerAssignments",
  VAULT_SIGNER_AUDIT_LOG: "vaultSignerAuditLog",
  COMPLIANCE_TEMPLATES: "complianceTemplates",
  COMPLIANCE_REQUIREMENTS: "complianceRequirements",
  AUDIT_TRAIL: "auditTrail",
  OBSERVABILITY: "observability",
  CURATED_ASSETS: "curatedAssets",
  SERVICE_LINKS: "serviceLinks",
};
