package health

import (
	"encoding/json"
	"log"
	"net/http"
	"os"
	"time"

	httpSwagger "github.com/swaggo/http-swagger"
)

// httpSwagger.WrapHandler serves whatever OpenAPI spec is registered with
// swag's global registry at runtime. That registration happens in the
// generated docs/docs.go's init(), which main.go blank-imports
// ("_ trovo-wallet-payment-history-engine/docs") - see that file's top-level
// @title/@version/... block, generated by running `swag init` from the
// module root.

// LivenessHandler godoc
//
//	@Summary		Liveness probe
//	@Description	Reports that the payment-history-engine process is running. Performs no
//	@Description	dependency checks, so it stays 200 even while a database or the Base RPC
//	@Description	node is unreachable - use GET /ready to decide whether the service is able
//	@Description	to do its job. Intended for container/orchestrator liveness checks. No
//	@Description	authentication required.
//	@Tags			Health
//	@Produce		json
//	@Success		200	{object}	LivenessResponse
//	@Router			/health [get]
func (s *Service) LivenessHandler(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, s.Liveness())
}

// ReadinessHandler godoc
//
//	@Summary		Readiness probe
//	@Description	Checks every backing dependency in parallel (the primary wallet database,
//	@Description	the RoachDB payment-history database, Redis when ENABLE_CACHING=1, and the
//	@Description	Base RPC node) and reports each one individually, alongside whether the
//	@Description	block-processing stream is still making progress. Returns 503 only when a
//	@Description	REQUIRED dependency (wallet_db or roach_db) is down. An optional dependency
//	@Description	being down, or the stream having stalled, is reported as "degraded" but
//	@Description	still returns 200 - restarting the container would not fix a network outage
//	@Description	or a quiet chain, so this deliberately avoids causing a restart loop. No
//	@Description	authentication required.
//	@Tags			Health
//	@Produce		json
//	@Success		200	{object}	ReadinessResponse	"Ready (status up, idle, or degraded)"
//	@Failure		503	{object}	ReadinessResponse	"A required dependency (wallet_db or roach_db) is down"
//	@Router			/ready [get]
func (s *Service) ReadinessHandler(w http.ResponseWriter, r *http.Request) {
	report, status := s.Readiness(r.Context())
	writeJSON(w, status, report)
}

// Serve starts a small HTTP server exposing the probes (and their Swagger UI).
//
// This service has no HTTP server of its own - it is a worker - so one is added
// purely for monitoring. It listens on HEALTH_PORT (default 8080) and serves
// only these endpoints plus /swagger/, which keeps the surface small enough to
// expose on the internal network without further thought.
//
// Runs in its own goroutine and never blocks the worker: a monitoring endpoint
// that could stall payment processing would be worse than no endpoint at all.
func Serve(s *Service) {
	port := os.Getenv("HEALTH_PORT")
	if port == "" {
		port = "8080"
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/health", s.LivenessHandler)
	mux.HandleFunc("/ready", s.ReadinessHandler)
	// Swagger UI, generated from the @swag annotations on the handlers above
	// (and the top-level block in main.go) via `swag init`. Served at
	// /swagger/index.html; the raw spec is at /swagger/doc.json.
	mux.HandleFunc("/swagger/", httpSwagger.WrapHandler)

	server := &http.Server{
		Addr:              ":" + port,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
	}

	go func() {
		log.Printf("[health] probes listening on :%s", port)
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			// A failure to bind must not take the engine down: payment
			// processing matters more than the ability to report on it.
			log.Printf("[health] probe server stopped: %v", err)
		}
	}()
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(body); err != nil {
		log.Printf("[health] failed to encode response: %v", err)
	}
}
