// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(String walletMode) {
    print('walletMode: $walletMode');
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return walletMode == "Testnet" ? androidTestNet : androidMainnet;
      case TargetPlatform.iOS:
        return walletMode == "Testnet" ? iosTestNet : iosMainnet;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidTestNet = FirebaseOptions(
    apiKey: 'AIzaSyBKdXjdmZDCNUkNn45nPf6T9BRtCROG0UE',
    appId: '1:572371578875:android:213ad7583e9ea30244255e',
    messagingSenderId: '572371578875',
    projectId: 'trovotech-website',
    storageBucket: 'trovotech-website.appspot.com',
  );

  static const FirebaseOptions iosTestNet = FirebaseOptions(
    apiKey: 'AIzaSyC6QC2-JjxUHg3jAjbQBIBty5YtBOnJfsw',
    appId: '1:572371578875:ios:fc95ede8ed5006ad44255e',
    messagingSenderId: '572371578875',
    projectId: 'trovotech-website',
    storageBucket: 'trovotech-website.appspot.com',
    iosClientId: '572371578875-uqpeb4pagtfm3leaobcjovfhri4eoc16.apps.googleusercontent.com',
    iosBundleId: 'com.trovo.wallet',
  );

  static const FirebaseOptions androidMainnet = FirebaseOptions(
    apiKey: 'AIzaSyA4eXXAzx6JcyUdNscm_mOgxQ_vdYp6Mvo',
    appId: '1:883904669467:android:3560253101ca2241d855be',
    messagingSenderId: '883904669467',
    projectId: 'trovo-infra-mainnet',
    storageBucket: 'trovo-infra-mainnet.appspot.com',
  );

  static const FirebaseOptions iosMainnet = FirebaseOptions(
    apiKey: 'AIzaSyC1Pa6HSM0GD3yzlofCfPSURggP3-aEKIw',
    appId: '1:883904669467:ios:4c2d3ff8ee21134ed855be',
    messagingSenderId: '883904669467',
    projectId: 'trovo-infra-mainnet',
    storageBucket: 'trovo-infra-mainnet.appspot.com',
    iosClientId: '883904669467-jfe5mukot91a3285td32v3k9f9e5950r.apps.googleusercontent.com',
    iosBundleId: 'com.trovo.wallet',
  );
}
